### ISSUE TITLE
Fix CSS for logo and title on readthedocs

### ISSUE THREAD

**Issue by clinssen** [nest/nest-simulator#1451]
The NEST Simulator logo does not show up on https://nest-simulator.readthedocs.io using Firefox 60.8. Also, the link text is rendered in white against an almost-white background, making it impossible to read.

The issue seems to be that [CSS "content"](https://developer.mozilla.org/en-US/docs/Web/CSS/content) needs to be placed after a `::before` or `::after` directive, but in our custom CSS ([_static/css/custom.css](https://github.com/nest/nest-simulator/blob/master/doc/_static/css/custom.css)) these are missing.

I suggest replacing

```css
.wy-side-nav-search>a, .wy-side-nav-search .wy-dropdown>a {
   content: url(../../_static/img/nest_logo.png);
}

.wy-side-nav-search {
	background: linear-gradient(45deg, #fff, #eee);
	color: #888;
    border-bottom: 1px solid #e1e4e5;
}
```

with

```css
.wy-side-nav-search>a::before {
   content: url(../../_static/img/nest_logo.png);
}

.wy-side-nav-search>a {
	color: #f63;
}

.wy-side-nav-search {
	background: linear-gradient(45deg, #fff, #eee);
	border-bottom: 1px solid #e1e4e5;
}
```

I don't know what element `.wy-dropdown` refers to and couldn't find this in the RTD sources or google.

**Comment by steffengraber** [comment]
The standard RTD theme is used. 'custom.css' just modifies it a bit. '.wy-dropdown' is part of the Sass files of the RTD theme. Therefore it will be overwritten here too. But as far as I can see, it's not that bad to leave it out.
With the replacement of '::before' or '::after' the text inside the link becomes visible. 
I have created an example with your changes here:
https://nest-simulator-sg.readthedocs.io/en/fix-1451/

How does it look like in Firefox 60.8?

**Comment by clinssen** [comment]
@steffengraber: thanks for testing this; the logo shows up fine on your link.

I had a meeting with @sarakonradi about NESTML docs, and we also talked about this CSS issue. There are now three elements in the top-left box: the logo, the header text ("NEST simulator user documentation") and the version (e.g. "stable" or "latest"). Probably this is a bit too much and we should stick with only the logo. The version also appears at the bottom-left of the page; it does so consistently across readthedocs so we should stick with this location.

The version string we can make disappear by
```css
.wy-side-nav-search .version {
    display: none;
}
```

I am not sure yet how to make the header text ("NEST simulator user documentation") disappear. We could just rename this "NEST Simulator", which might look OK (I'll leave this decision up to you).

Another thing: visitors might expect that clicking the logo leads them back to the index/landing page, as this is a common pattern in websites. However, the link actually points to contents.html.
