### ISSUE TITLE
docopt is missing in the Docker image

### ISSUE THREAD

**Issue by vvorobjov** [nest/nest-simulator#3452]
**Describe the bug**
The Python `docopt` module is missing when trying to run `nest-server-mpi` in the Docker container

**To Reproduce**
1. Use docker compose file
```
services:

    nest-server:
        image: docker-registry.ebrains.eu/nest/nest-simulator:3.8
        # volumes:
        #     - ./:/experiment
        environment:
            NEST_CONTAINER_MODE: "nest-server-mpi"
            NEST_SERVER_BUFFER_SIZE: 65535
            NEST_SERVER_HOST: "0.0.0.0"
            NEST_SERVER_MODULES: 'import nest; import numpy; import os; import json; import sys'
            NEST_SERVER_PORT: 9000
            NEST_SERVER_RESTRICTION_OFF: 1
            NEST_SERVER_ENABLE_EXEC_CALL: 1
            NEST_SERVER_DISABLE_AUTH: 1
            NEST_SERVER_DISABLE_RESTRICTION: 1
            NEST_SERVER_STDOUT: 1
            OMPI_ALLOW_RUN_AS_ROOT: 1
            OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
```
2. Launch the service
```
docker compose -f docker-compose.yaml up nest-server
```
3.  In the output you see
```
nest-server-1  | Traceback (most recent call last):
nest-server-1  |   File "/opt/nest/bin/nest-server-mpi", line 16, in <module>
nest-server-1  |     from docopt import docopt
nest-server-1  | ModuleNotFoundError: No module named 'docopt'
nest-server-1  | --------------------------------------------------------------------------
nest-server-1  | Primary job  terminated normally, but 1 process returned
nest-server-1  | a non-zero exit code. Per user-direction, the job has been aborted.
nest-server-1  | --------------------------------------------------------------------------
nest-server-1  | --------------------------------------------------------------------------
nest-server-1  | mpirun detected that one or more processes exited with non-zero status, thus causing
nest-server-1  | the job to be terminated. The first process to do so was:
nest-server-1  | 
nest-server-1  |   Process name: [[3258,1],0]
nest-server-1  |   Exit code:    1
nest-server-1  | --------------------------------------------------------------------------
nest-server-1 exited with code 1
```

**Expected behavior**
It is expected that the distributed nest-server is launched in the container

**Screenshots**

**Desktop/Environment (please complete the following information):**
 - OS: [Ubuntu-24.04]
 - Shell: bash
 - Python-Version: Python 3.12
 - Docker version 27.1.1, build 6312585
 - NEST-Version: 3.8, 3.7
 - Installation: docker-registry.ebrains.eu/nest/nest-simulator
