### ISSUE TITLE
Use codecov.io to generate code coverage reports

### ISSUE THREAD

**Issue by sanjayankur31** [nest/nest-simulator#388]
Just a nice to have. According to https://github.com/codecov/example-python, just two new lines are required in the travis.yml file:

``` yml
install:
    pip install codecov
after_success:
    codecov
```

Nose already supports codecoverage as shown here: https://github.com/codecov/example-python#using-nosetests.

Github/codeconv integration: https://github.com/integrations/codecov

Of course, codecov.io is free to use for public repositories, similar to travis. 

An example can be seen here:
https://github.com/arvidn/libtorrent/pull/782
